# Generated by Django 4.0.5 on 2022-06-26 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='mbti',
        ),
        migrations.RemoveField(
            model_name='board',
            name='name',
        ),
    ]
